<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introducción-a-Numpy" data-toc-modified-id="Introducción-a-Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introducción a Numpy</a></span></li><li><span><a href="#Listas-n-dimensionales:" data-toc-modified-id="Listas-n-dimensionales:-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Listas n-dimensionales:</a></span><ul class="toc-item"><li><span><a href="#Comentarios-acerca-de-la-escalabilidad-(Big-O-notation-y-por-qué-es-importante-Numpy)" data-toc-modified-id="Comentarios-acerca-de-la-escalabilidad-(Big-O-notation-y-por-qué-es-importante-Numpy)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Comentarios acerca de la escalabilidad (Big-O notation y por qué es importante Numpy)</a></span></li></ul></li><li><span><a href="#NumPy-ndarray:-Un-objeto-para-arreglos-multidimensionales" data-toc-modified-id="NumPy-ndarray:-Un-objeto-para-arreglos-multidimensionales-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>NumPy <code>ndarray</code>: Un objeto para arreglos multidimensionales</a></span><ul class="toc-item"><li><span><a href="#Creando-Arreglos-de-n-dimensiones-usando-NumPy" data-toc-modified-id="Creando-Arreglos-de-n-dimensiones-usando-NumPy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Creando Arreglos de n dimensiones usando <code>NumPy</code></a></span></li><li><span><a href="#Arreglos-predefinidos-en-numpy:" data-toc-modified-id="Arreglos-predefinidos-en-numpy:-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Arreglos predefinidos en numpy:</a></span></li><li><span><a href="#Datatypes-en-ndarrays" data-toc-modified-id="Datatypes-en-ndarrays-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Datatypes en <code>ndarrays</code></a></span><ul class="toc-item"><li><span><a href="#Uso-explícito-de-datatypes" data-toc-modified-id="Uso-explícito-de-datatypes-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Uso explícito de datatypes</a></span></li><li><span><a href="#Conversión-de-datatypes" data-toc-modified-id="Conversión-de-datatypes-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Conversión de datatypes</a></span></li><li><span><a href="#Aritmética-con-arreglos-de-Numpy" data-toc-modified-id="Aritmética-con-arreglos-de-Numpy-3.3.3"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span>Aritmética con arreglos de Numpy</a></span></li><li><span><a href="#Indexación-y-extracción-de-subconjuntos-de-arreglos" data-toc-modified-id="Indexación-y-extracción-de-subconjuntos-de-arreglos-3.3.4"><span class="toc-item-num">3.3.4&nbsp;&nbsp;</span>Indexación y extracción de subconjuntos de arreglos</a></span></li><li><span><a href="#Arreglos-multidimensionales" data-toc-modified-id="Arreglos-multidimensionales-3.3.5"><span class="toc-item-num">3.3.5&nbsp;&nbsp;</span>Arreglos multidimensionales</a></span><ul class="toc-item"><li><span><a href="#Arreglos-tridimensionales" data-toc-modified-id="Arreglos-tridimensionales-3.3.5.1"><span class="toc-item-num">3.3.5.1&nbsp;&nbsp;</span>Arreglos tridimensionales</a></span></li><li><span><a href="#Indexando-con-subconjuntos" data-toc-modified-id="Indexando-con-subconjuntos-3.3.5.2"><span class="toc-item-num">3.3.5.2&nbsp;&nbsp;</span>Indexando con subconjuntos</a></span></li><li><span><a href="#Indexación---representación-gráfica" data-toc-modified-id="Indexación---representación-gráfica-3.3.5.3"><span class="toc-item-num">3.3.5.3&nbsp;&nbsp;</span>Indexación - representación gráfica</a></span></li></ul></li></ul></li><li><span><a href="#Indexación-lógica" data-toc-modified-id="Indexación-lógica-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Indexación lógica</a></span></li></ul></li><li><span><a href="#¡Felicidades!-🎉" data-toc-modified-id="¡Felicidades!-🎉-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>¡Felicidades! 🎉</a></span></li></ul></div>

# Introducción a Numpy

Ejercicios tomados de https://github.com/wesm/pydata-book, basados en el libro [Python for data Analysis de Wes McKinney](http://amzn.to/2vvBijB).

Si bien __Numpy__ en si mismo no provee funcionalides de modelamiento o aplicaciones científicas directamente, el comprender cómo funcionan los arreglos en esta librería sin duda servirá de ayuda para comprender otras herramientas basadas en estos arreglos, como __Pandas__. Numpy en si mismo es un tema muy grande, por lo que se intentará dar énfasis en los siguientes puntos:

__¿Por qué usar Numpy?__

- Permite operaciones vectorizadas sobre arreglos (arrays) para limpieza y manipulación de datos, filtrado, transformación, y otro tipo de operaciones
- Implementación nativa de algoritmos comunes como ordenamiento (sorting), búsqueda (search), y operaciones propias de conjuntos, tales como:
  - Extraer valores únicos
  - Categorizar valores no categóricos
- Implementa métodos para estadística descriptiva simple, así como herramientas para agrupar/sintetizar datos: promedios, sumas, cuentas, etc.
- Manipulación de datos para tareas de fusión (merging) y unión (join)
- Expresión de operaciones lógicas ("_si ocurre esto, entonces haz esto_") en términos de operaciones vectorizadas, en vez de operaciones iterativas como bucles `for` y `while`.
- Manipulación de datos agrupados

Mientras que **Numpy** provee una base para tareas de procesamiento genérico de datos, es probable que usuarios provenientes de las áreas de la analítica y estadística deseen usar **Pandas**, al presentar este una representación de datos en forma tabular.

Sin embargo, numpy está diseñado para _operar eficientemente_ sobre grandes conjuntos de datos.
Un repaso rápido a las listas en python

Listas unidimensionales:

```python
some_list_1d = [15, 3, 21, 8, 3, 12, 5, 3]
```

![1d_array](figures/array_single.png)

¿Cómo se accede al número 21 en la lista?

In [ ]:
some_list_1d = [15, 3, 21, 8, 3, 12, 5, 3]
some_list_1d[2]

Listas 2d:

```python
some_list_2d = [[0, 0, 0, 0, 1],
                [0, 0, 0, 1, 1],
                [0, 0, 1, 1, 1],
                [0, 0, 0, 1, 1],
                [0, 0, 0, 0, 1]]

```

![2d_array](figures/2d_array.png)

¿Cómo se accede al 1 de la esquina inferior derecha?

In [ ]:
some_list_2d = [[0, 0, 0, 0, 1],
                [0, 0, 0, 1, 1],
                [0, 0, 1, 1, 1],
                [0, 0, 0, 1, 1],
                [0, 0, 0, 0, 1]]

some_list_2d[4] # primero indexar por el primer eje

In [ ]:
some_list_2d[4][4] # luego indexar por el segundo eje

# Listas n-dimensionales:

![2d_array](figures/3d_array.png)

- ¿Cuál es el primer nivel?
- ¿Cuál es el segundo nivel?
- ¿A qué nivel corresponden los números que se ven en la figura?
- ¿Cómo accedemos al valor en la esquina inferior izquierda en `z=1`?

In [ ]:
some_list_3d = [[[0, 0, 0], [1, 2, 3], [1, 2, 3], [1, 2, 0]],
                [[0, 0, 0], [1, 2, 3], [1, 2, 3], [1, 2, 1]],
                [[0, 0, 0], [1, 2, 3], [1, 2, 3], [1, 2, 2]],
                [[0, 0, 0], [0, 0, 0], [1, 2, 3], [1, 2, 3]]]

print(some_list_3d[0],"\n")
print(some_list_3d[0][3],"\n")
print(some_list_3d[0][3][1])

In [ ]:
#Una lista no debe ser necesariamente cuadrada:

some_jagged_list = [[15, 2, 8, 5, 3], 
                    [3, 3, 7],
                    [9, 1, 16, 13],
                    [],
                    [5]]
some_jagged_list    
some_jagged_list[2] 
some_jagged_list[2][0]
some_jagged_list[2][3]


Esto es sólo un recordatorio. Numpy y pandas tienen semejanzas a las listas en python, pero no son lo mismo! 
¡Para usar Pandas y Numpy hay que explicitamente incluir la biblioteca!

In [ ]:
# esta celda es sólo para configurar las librerías

import numpy as np

# Inicializa los números aleatorios (semilla) 
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html

np.random.seed(12345) 

Consideremos el siguiente ejemplo:

In [ ]:
import numpy as np
my_arr = np.arange(1000000) # crea una lista usando numpy
my_list = list(range(1000000)) # crea una lista usando python puro

my_arr
#my_list

In [ ]:
# %time mide el tiempo de ejecución de cada línea
# más información en https://jakevdp.github.io/PythonDataScienceHandbook/01.07-timing-and-profiling.html

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

<div class="alert alert-info">
Si bien un tiempo del orden de los milisegundos no parece ser mucho, este tiempo puede acumularse y crecer considerablemente si se trabaja sobre un dataset muy grande.
</div> 

## Comentarios acerca de la escalabilidad (Big-O notation y por qué es importante Numpy)

Al hablar de la eficiencia de numpy es inevitable mencionar algunas nociones básicas sobre escalabilidad. En ciencias de la computación, se utiliza lo que se conoce como _Big-O Notation_ para describir la manera en que el número de operaciones requeridas por un algoritmo _escala_ (aumenta en tamaño) en la medida que aumenta la información con la que opera. 

Big-O notation, de modo simple y sin querer profundizar en contenidos de ciencias de computación, nos dice cuánto tiempo se demora un algoritmo en procesar un _dataset_, y nos da una noción de cómo este tiempo aumenta a medida que el _dataset_ aumenta en tamaño. 


Por ejemplo, si se tiene un algoritmo A, de orden $n$ o $O(n)$ , esto quiere decir que si este algoritmo se demora 1 segundo en procesar mil líneas de texto ($n=1.000$), entonces es esperable que este mismo algoritmo se demore 5 segundos en procesar $n=5.000$.

Por otro lado, si se tiene un algoritmo B, cuyo orden es de $O(n^2)$, el cual demora 1 segundo en procesar $n=1000$, entonces es esperable que este algoritmo se demore 25 segundos en procesar $n=5.000$ datos. 

En general en el procesamiento de datos se asocia el valor de $n$ al tamaño del dataset. Es de esta manera que si se considera el análisis de un dataset muy grande, digamos del orden de trillones de datos, entonces la diferencia entre $O(n)$ y $O(n^2)$ se vuelve de suma importancia.

Considerar además de la notación _Big-O_ no habla específicamente del tiempo _cronometrado_ que dura la ejecución de un algoritmo, sino más bien de cómo este algoritmo escala en la medida que crece $n$. Se considera entonces que un algoritmo $O(n)$ escala __mejor__ que uno $O(n^2)$, pero para dataset pequeños esta diferencia puede no ser muy notoria.

Es importante entender los órdenes de complejidad pues permite establecer comparaciones. 

Algunos recursos adicionales

- http://bigocheatsheet.com/
- https://stackoverflow.com/a/487278/5819113


# NumPy `ndarray`: Un objeto para arreglos multidimensionales

Uno de los aspectos clave de Numpy es el arreglo _N-dimensional_, o `ndarray`. Estos permiten operaciones matemáticas sobre bloques completos de datos.

In [ ]:
import numpy as np

# Genera números aleatorios provenientes de una distribución normal(0,1) de 2 x 3 dimensiones: 2 filas y tres columnas
# Para generación de otro tipos de distribuciones revisar:
# https://docs.scipy.org/doc/numpy/reference/routines.random.html

data = np.random.randn(2, 3)
print(data)

In [ ]:
print(data * 10)
data

In [ ]:
print(data + data)

In [ ]:
data.shape # tamaño del array

In [ ]:
print(data.dtype)
print(data.shape)
print(data.ndim)
print(data)

<div class="alert alert-info">
Es importante entender lo básico de `numpy`, pues permite comprender otras librerías como pandas, y manipular datos de la manera más eficiente
</div> 

## Creando Arreglos de n dimensiones usando `NumPy`

In [ ]:
data1 = [6, 7.5, 8, 0, 1] # lista de datos
arr1 = np.array(data1)
arr1

In [ ]:
print(arr1.ndim) #dimensiones del arregolo
print(arr1.shape)# arroja los largos de las correspondientes dimensiones en una tupla '()'

<div class="alert alert-info">
NOTA: Una forma rápida de acceder a la documentación de algún atributo o función es a través de la función <b>help()</b>.
</div> 

In [ ]:
help(np.ndim)
help (np.shape)

In [ ]:
# anidar dos listas en una lista produce un arreglo multidimensional
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(data2)
arr2

In [ ]:
print(arr2.ndim) # dos dimensiones
print(arr2.shape) # dos filas, cuatro columnas

A menos que se explicite, `np.array` intenta inferir un tipo de dato (data type) de los elementos en el arreglo. El resultado de esto es almacenado en un atributo especial, `dtype`. 

In [ ]:
print(arr1.dtype) # contiene números con decimales Nota: arr1 es array([6. , 7.5, 8. , 0. , 1. ])
print(arr2.dtype) # contiene sólo números enteros Nota arr2 es array([[1, 2, 3, 4], [5, 6, 7, 8]])

## Arreglos predefinidos en numpy:
$ zeros (tupla)$ genera un arreglo de las dimensiones especificadas en la tupla.

$  numpy.arange([start, ]stop, [step, ]dtype=None)$ genera un arreglo desde el comienzo start hasta stop (menor estricto) con paso step y tipo de dato dtype


In [ ]:
np.zeros(10) #Generar un arreglo de 10 0s

In [ ]:
np.zeros((3, 6)) #Genera un arreglo de 3x6 de zeros

In [ ]:
#arr3 = np.arange(15) 
#arr3.dtype
arr3 = np.arange(0, 10,1, dtype='float64')
arr3.dtype

In [ ]:
np.empty((2, 3, 2))

<div class="alert alert-warning">
<i>empty</i>, a diferencia de <i>zeros</i>, no inicializa los valores en cero, lo que permite mejoras en la velocidad marginalmente superiores. Esto significa que no es seguro que <i>empty</i> regrese ceros únicamente, y debe ser usado con precaución.
</div>


Otros arreglos pueden ser `ones`, `ones_like`, `full`.}
Para más detalles ver:

- https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html 

- https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html

- https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html

## Datatypes en `ndarrays`

Un *datatype* es un objeto especial que contiene información acerca de los datos que almacena un arreglo. Estos poseen características tales como

- Cantidad de bits usados para representar un número: esto influye en los números máximos posibles de representar usando un data type en particular, y se especifican generalmente con la cantidad como sufijo i.e. `int8` es de tamaño 8 bits, y `float128` es de tamaño 128 bits.

- Presencia de signo (_unsigned_ (`uint8`) versus _signed_ (`int8`))

- Si es decimal (float versus integer)

In [ ]:
# ejemplos de data types
import numpy as np
# enteros
int_types = ["int8", "uint8", "int16", "uint16"] #tipos de enteros en NumPy
for x in int_types:
    print(np.iinfo(x))

In [ ]:
import numpy
# ejemplos de tata types flotantes
float_types = ["float16", "float32", "float64"]
for x in float_types:
    print(np.finfo(x))

Notar el campo de `precision`. ¿Qué significa? ¿Cómo varían los campos `min` y `max`?

Esto permite a numpy realizar optimizaciones especiales según el dtype siendo usado. Estas optimizaciones pueden ser bien de uso de memoria o velocidad. 

Un ejemplo de optimización puede verse en https://www.dataquest.io/blog/pandas-big-data/

### Uso explícito de datatypes

In [ ]:
# especificar dtype en la definición de arreglo
arr1 = np.array([1, 2, 3], dtype=np.float64)
print (arr1)
print(arr1.dtype)

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
print (arr1)
print (arr2)
print(arr2.dtype)

### Conversión de datatypes

In [ ]:
# convertir de un data type a otro
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype, "\n") # "\n" imprime un salto de línea

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

Notar que la conversión de decimal a entero redondea o aproxima los valores a su parte entera

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.dtype)


In [ ]:
arr.astype(np.int32)

también es posible convertir textos como números a números.  Es importante tener cuidado en la operación anterior, pues `np.string_` tiene un tamaño fijo y puede truncar datos de manera inesperada

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

### Aritmética con arreglos de Numpy

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)

In [ ]:
arr * arr # Eleva al cuadrado cada elemento


In [ ]:
arr - arr

In [ ]:
1 / arr # calcula 1/x por cada valor del arreglo

In [ ]:
arr ** 0.5 # raíz cuadrada de cada valor del arreglo

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
print (arr2 > arr, "\n") # es cada elemento de arr2 mayor que su equivalente en arr?
print (arr > arr2)

### Indexación y extracción de subconjuntos de arreglos

`ndarray` se comporta en gran manera como listas en python:

In [ ]:
arr = np.arange(10)
print(arr)

In [ ]:
print(arr[5])
print(arr[5:8])

In [ ]:
arr[5:8] = 12 # asignar 12 a los valores en el rango 5-8
print(arr)

Una diferencia importante, sin embargo, es que subconjuntos de un `ndarray` son realmente _vistas_ del ndarray original.  Esto significa que la extracción de subconjuntos no produce una copia de los datos, y que *cualquier modificación en el subconjunto se verá reflejado en el conjunto original y viceversa.

Dado que numpy está diseñado para trabajar con _grandes_ conjuntos de datos, es posible imaginar los problemas de rendimiento resultantes de estar copiando constantemente los datos.

In [ ]:
# extraer un subconjunto
arr_slice = arr[5:8]
print(arr_slice)
print(arr)

In [ ]:
# reemplazar un solo valor en el subconjunto
arr_slice[1] = 12345
print(arr) # ver cambio en arreglo original

In [ ]:
arr_slice[:] = 64 # reemplazar todos los valores en el subconjunto con el valor 64
print(arr) # ver cambios en arreglo original

Si se desea una copia explícita, se debe usar `copy()`:

In [ ]:
arr_slice_copy = arr_slice.copy() # hacer una copia del subconjunto anterior
print(arr_slice_copy)
arr_slice_copy[:] = 0 # reemplazar todos los valores por cero
print(arr_slice_copy) # 
print(arr) # cambios no son reflejados!

### Arreglos multidimensionales
Un arreglo, visualmente, puede representarse como una matriz:

![array-example](figures/array.png)


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

In [ ]:
# recordar que en numpy al igual que en python, los arreglos o listas comienzan en 0
print(arr2d[2]) # accede a la tercera fila

In [ ]:
print(arr2d[0][2])

In [ ]:
print(arr2d[0, 2])

#### Arreglos tridimensionales

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # arreglo de 2x2x3
print(arr3d)

In [ ]:
arr3d.shape

In [ ]:
arr3d[0]

In [ ]:
arr3d[1, 0] # acceder a la segunda fila, primer elemento

#### Indexando con subconjuntos

**Recordar:** ¡listas comienzan en cero!

In [ ]:
print(arr2d)

In [ ]:
arr2d[:2] # accede a todos los elementos del primer nivel desde 0 hasta 1 (el 2 no se incluye!)

In [ ]:
arr2d[:2, 1:] # igual al anterior, pero de niveles 0 y 1

In [ ]:
arr2d[1, :2] # accede a los elementos (1, 0) y (1, 1)

In [ ]:
arr2d[:2, 2] # accede a los elementos 0-1 en el primer nivel, y al tercer elemento del segundo nivel

In [ ]:
arr2d[:, :1] # accede a todos los elementos del primer nivel, y a el primer elemento del segundo nivel

In [ ]:
arr2d[:2, 1:] = 0 # iguala un subconjunto a cero
print(arr2d)

#### Indexación - representación gráfica
![array_slicing](figures/array_slicing.png)

## Indexación lógica

La indexación lógica implica la utilización de máscaras o *masking*. Una máscara es un arreglo auxiliar que se utiliza para indexar otros arreglos.

Es posible extraer subconjuntos de un arreglo en base a condiciones lógicas. Una condición lógica puede ser, por ejemplo

- `age > 28` (Mayor a)
- `name == "Manuel"` (Igual)
- `name != "Manuel"` (No igual)

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # produce un arreglo de 1x7
data = np.random.randn(7, 4) # produce una matriz de 7x4 de números aleatorios

In [ ]:
print(names)

In [ ]:
print(data)

In [ ]:
names == 'Bob' # coindice en los índices 0 y 3

In [ ]:
data[names == 'Bob']

El arreglo resultante es aquel en los cuales `names == "Bob"` es `True`, es decir, las filas 0 y 3

In [ ]:
data[names == 'Bob', 2:]

In [ ]:
data[names == 'Bob', 3]

In [ ]:
names != 'Bob' # != significa "no es igual a"
data[~(names == 'Bob')] # o alternativamente, '~' es un operador NOT que niega (invierte) los resultados

In [ ]:
cond = names == 'Bob' # cond es una máscara
print(cond)

In [ ]:
data[~cond] # extrae los valores de data en los cuales se cumpla cond == False (notar el ~)

Es posible utilizar lógica binaria (o booleana) para construir máscaras complejas

In [ ]:
#['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

mask_1 = (names == 'Bob') 
mask_2 = (names == 'Will')
print(mask_1,"\n")
print(mask_2)

In [ ]:
mask = mask_1 | mask_2 # '|' (pipe) es equivalente a un OR
print(mask)

Notar en en numpy los operadores lógicos `or` y `and` no funcionan, y deben usarse `|` y `&` en reemplazo.

In [ ]:
#[[ 0.75836315 -0.66052433  0.86258008 -0.0100319 ]
# [ 0.05000936  0.67021559  0.85296503 -0.95586885]
# [-0.02349332 -2.30423388 -0.65246884 -1.21830198]
# [-1.33260971  1.07462269  0.72364151  0.69000185]
# [ 1.00154344 -0.50308739 -0.62227423 -0.92116861]
# [-0.72621349  0.22289555  0.0513161  -1.15771947]
# [ 0.81670694  0.43360961  1.01073695  1.82487521]]


data[mask]

In [ ]:
data[data < 0] = 0 # reemplazar con un cero todos los valores que sean menores a cero
print(data)

In [ ]:
# ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data[names != 'Joe'] = 7 # Reemplaza con un 7 donde se cumpla la condición
data

# ¡Felicidades! 🎉

Esto concluye lo más fundamental de numpy. Algunas cosas que puedes hacer para mejorar:

- 100 ejercicios de Numpy: https://github.com/rougier/numpy-100
- Tutorial completo de numpy http://scipy-lectures.org/intro/numpy/index.html

Con esto es posible avanzar a **Pandas** 🐼